### ISSUE TITLE
Math expressions cannot be used as array indices

### ISSUE THREAD

**Issue by zauberparacelsus** [MyWorldLLC/Chipmunk#23]
When an array index is calculated by math expression, it will not work if the expression is in the index bracket.

So, code such as this will not work:
`arr[x-1] = y`

**Comment by danielperano** [comment]
I believe this may be the same issue as #28.

The following test script behaves as expected:
`module test
import chipmunk.system.println

def main(){
    var x = 1
    var list = [1, 2]
    list[x - 1] = 2
    println(list)
    println(list[x - 1])
}`

However, if I rewrite the array index expression without spaces (as in your example) the compilation fails because the lexer treats `x-1` as the sequence ["x", "-1"], which is not a valid expression. I'll leave this open until #28 is fixed, however.

**Comment by danielperano** [comment]
Fixed by 8e8969d.
