### ISSUE TITLE
Extend importJava to support statics

### ISSUE THREAD

**Issue by zauberparacelsus** [MyWorldLLC/Chipmunk#32]
The `importJava` method does not work properly when importing statics, as their constructors are private and therefor the linker cannot bind to them.

**Comment by danielperano** [comment]
The `importJava` functionality is awkward right now - you can't directly use the returned result for static dispatch (even once the linker supports it) because it's a wrapper instance, and you have to call a method on the wrapper to instantiate the class after obtaining it.

I'll split the `importJava` into two functions: one which imports and returns the unwrapped class object (which later on can be used for static invocations), and one which takes the class name and an argument list and instantiates the class, returning an instance - something like `newJava("some.jvm.Class", [arg1, arg2]).

**Comment by danielperano** [comment]
Fixed by 76c448d.

(Note that support for statics resides in the linker - tracked by #16)
