### ISSUE TITLE
Feature: Import aliasing

### ISSUE THREAD

**Issue by zauberparacelsus** [MyWorldLLC/Chipmunk#35]
One useful feature in Python is that imported modules and objects can be aliased, giving them a different name.  This is useful if, for example, you want to use a third-party module, but it is using names for its objects that you are already using, or already wish to use.  It is also useful if a module or object has a cumbersome name, allowing you to alias it to something shorter and easier to type.

Examples:
```
import exampleModule as exMod
from sampleModule import SomeOverlyLongWindedFunctionName as someFunc
```

**Comment by danielperano** [comment]
Chipmunk already does support aliased imports in this form - see [ModuleSingleFromImportAliased.chp](https://github.com/MyWorldLLC/Chipmunk/blob/master/Lang/src/test/resources/chipmunk/ModuleSingleFromImportAliased.chp)

The top import is not supported, however, as modules are not importable as objects - you could alias a single import as follows though:

`import exampleModule.someSymbol as symbol`

**Comment by zauberparacelsus** [comment]
lol, I need to pay more attention to the test scripts :D 

I take it that when you import a module, all of its objects are imported into the current module's namespace, which thereby means that aliasing entire modules isn't needed?

**Comment by danielperano** [comment]
> I take it that when you import a module, all of its objects are imported into the current module's namespace, which thereby means that aliasing entire modules isn't needed?

Sort of - your two options for imports are star imports (`import module.*`, `from module import *`), which behaves exactly as you described, and symbol-specific imports. If names collide on star imports, then you need to resolve it by using an alias.

The goal was to make modules behave more like Java's packages and less like objects in and of themselves - Python's modules are often used in such a way that they're almost global classes, which isn't the best design pattern to use. Modules should be a home for importable code (which can, if necessary, include global state), but they shouldn't take the place of objects & classes - that's why you can't import a module directly in Chipmunk.
